project:
    project_name: Questionnaire data analyses
    description: Questionnaire data analyses code from ART piplot analyses
    version: 0.0 d

input_data:
    data_location: mock
    local_directory: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: https://github.com/RADAR-base-Analytics/questionnairedataanalyses
      feature_groups:
          - QuestionnaireDataAnalyses

output_data:
    output_location: local
    local_directory: output
    data_format: csv
    compress: false
