project:
    project_name: Questionnaire Time Features
    description: Questionnaire data analyses code from ART pilot analyses
    version: 0.0

input_data:
    data_location: mock
    local_directory: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: https://github.com/RADAR-base-Analytics/questionnairetimefeatures
      feature_groups:
          - QuestionnaireTimeFeatures
      feature_names:
        - all

output_data:
    output_location: local
    local_directory: output
    data_format: csv
    compress: false
