project:
    project_name: Questionnnair data analyses
    description: Questionnaire data analyses code from ART piplot analyses
    version: 0.0

input_data:
    data_location: local
    local_directory: /Users/heetsankesara/work/ART/data_cleaning/questionnaire_data/
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: /Users/heetsankesara/work/RADAR/radar-pipeline/questionnnairdataanalyses
      feature_groups:
          - QuestionnnairDataAnalyses

output_data:
    output_location: local
    local_directory: passive_output
    data_format: csv
    compress: false
