project:
    project_name: Questionnaire Time Features
    description: Questionnaire data analyses code from ART pilot analyses
    version: 0.0

input:
    source_type: local # couldbe mock, local, sftp, s3
    config:
        # In case of sftp, use the following format
        # sftp_host:
        # sftp_source_path:
        # sftp_username:
        # sftp_private_key:
        # sftp_target_path:
        # In case of s3, use the following format
        #       aws_access_key_id:
        #       aws_secret_access_key:
        #       region_name:
        #       s3_access_url:
        #       bucket:
        #       prefix:
        # In case of local or Mock, use the following format
        source_path: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: 'https://github.com/RADAR-base-Analytics/questionnairetimefeatures'
      feature_groups:
          - QuestionnaireTest
      feature_names:
        - all

output:
    output_location: local # can be local, postgres, sftp
    config:
        target_path: output/ques_data
    data_format: csv
    compress: false
